openapi: 3.0.4
info:
  title: Sentiment Analysis
  description: >-
    Sentiment Analysis is a simple tool for analyzing the sentiment of a text.
    It returns the sentiment score and the sentiment label.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/sentimentanalysis:
    post:
      summary: Analyze Sentiment
      description: Analyze the sentiment of a body of text
      operationId: sentimentanalysis
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  comparative: 0.25
                  sentimentText: positive
                  sentiment: 3
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to analyze the sentiment of
              required:
                - text
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
sampleRequest:
  text: I'm so excited that tomorrow is going to be sunny! Can't wait!
